blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

bookmark/urls.py
from django.conf.urls import url
from bookmark.views import *

urlpatterns = [
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

    # Example: /add/
    url(r'^add/$',
        BookmarkCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        BookmarkChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        BookmarkUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        BookmarkDeleteView.as_view(), name="delete",
    ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView) :
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView) :
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>북마크 변경 - {{user}}</h1>

    <table class="change-list table-striped">
        <tr>
            <th>제목</th>
            <th>주소</th>
            <th>작성자</th>
            <th>업데이트</th>
            <th>삭제</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">업데이트</a></td>
            <td><a href="{% url 'bookmark:delete' item.id %}">삭제</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}


<!--class="table table-hover table-striped"  -->

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>북마크 삭제</h1>

    <form action="" method="post">{% csrf_token %}
        <p>"{{ object }}"를 정말로 삭제하시겠습니까?</p>
        <button type="submit" class="btn btn-default">북마크 삭제</button>
    </form>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">
    <h1>{{ object.title }}</h1>
<br>
    <ul>
        <li class="nono">주소: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>북마크 생성/업데이트 - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>북마크를 생성 또는 업데이트 할 수 있는 곳입니다.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.url.label_tag }} {{ form.url }}
        </div>

    </fieldset>

    <div class="submit-row">
        <button type="submit" class="btn btn-default">북마크 생성</button>
        <!-- <button type="hidden" name="next" class="btn btn-default" value="{{ next }}"></button> -->
    </div>


    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">
    <h1>북마크 목록</h1>
    <br>
    <ul>
        {% for bookmark in object_list %}
            <li class="nono"><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
            <br>
        {% endfor %}
    </ul>
</div>
{% endblock %}