blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import TagField
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()
    owner = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table  = 'blog_posts'
        ordering  = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

blog/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

#--- TemplateView
class TagTV(TemplateView) :
    template_name = 'tagging/tagging_cloud.html'

#--- ListView
class PostLV(ListView) :
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class TestPostLV(ListView) :
    #model = Post
    #queryset = Post.objects.all()[:5]
    #template_name = 'blog/post_all.html'
    template_name = 'blog/post_test.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        return Post.objects.filter(Q(content__icontains = self.kwargs['word'])).distinct()

    def get_context_data(self, **kwargs):
        context = super(TestPostLV, self).get_context_data(**kwargs)
        context['SearchWord'] = self.kwargs['word']
        return context

class PostTOL(TaggedObjectList) :
    model = Post
    template_name = 'tagging/tagging_post_list.html'

#--- DetailView
class PostDV(DetailView) :
    model = Post

#--- ArchiveView
class PostAV(ArchiveIndexView) :
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView) :
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView) :
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView) :
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView) :
    model = Post
    date_field = 'modify_date'

#--- FormView
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form) :
        schWord = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView) :
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView) :
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/ch16_post_archive.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    {% include "blog/post_archive_snippet.html" %}
</div>

</div>
{% endblock %}

blog/templates/blog/ch16_post_archive_snippet.html
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div class="container">
	<h2>블로그 목록</h2>
	<a href="{% url 'blog:add' %}" class="btn btn-primary" role="button">추가</a>
	<a href="{% url 'blog:change' %}" class="btn btn-default" role="button">변경</a>
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>제목</th>
	      <th>설명</th>
	      <th>날짜</th>
	    </tr>
	  </thead>
          {% for post in posts %}
	  <tbody>
	    <tr>
	      <td><a href='{{ post.get_absolute_url }}'/>{{ post.title }}</td>
	      <td>{{ post.description }}</td>
	      <td>{{ post.modify_date|date:"N d, Y" }}</td>
	    </tr>
	  </tbody>
          {% endfor %}
	</table>

	<div>
	    <span>
	        {% if page_obj.has_previous %}
	            <a href="?page={{ page_obj.previous_page_number }}">이전 페이지</a>
	        {% endif %}

	        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}

	        {% if page_obj.has_next %}
	            <a href="?page={{ page_obj.next_page_number }}">다음 페이지</a>
	        {% endif %}
	    </span>

	</div>
</div>

{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h1>{% now "N d, Y" %}까지의 포스트 아카이브</h1>
<ul>
    {% for date in date_list %}
    <li class="no" style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li class="no">{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h1>{{ day|date:"N d, Y" }}의 포스트 아카이브</h1>

<div>
    <ul>

        {% for post in object_list %}
        <li class="nono">{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h1>{{ month|date:"N, Y" }}의 포스트 아카이브</h1>
<br>
<div>
    <ul>
        {% for post in object_list %}
        <li  class="nono">{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h1>{{ year|date:"Y" }}의 포스트 아카이브</h1>

<ul>
    {% for date in date_list %}
    <li class="nono" style="display: inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li class="nono">{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>포스트 변경 - {{user}}</h1>

    <table class="change-list table-striped">
        <tr>
            <th>제목</th>
            <th>설명</th>
            <th>작성자</th>
            <th>업데이트</th>
            <th>삭제</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id %}">업데이트</a></td>
            <td><a href="{% url 'blog:delete' item.id %}">삭제</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>포스트 삭제</h1>

    <form action="" method="post">{% csrf_token %}
        <p>"{{ object }}"를 정말로 삭제하시겠습니까?</p>
        <button type="submit" class="btn btn-default">포스트 삭제</button>
    </form>

</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h2>{{ object.title }}
<a href="{% url 'blog:index' %}" class="btn btn-primary" role="button">목록</a></h2>

<p class="other_posts">
    {% if object.get_previous_by_modify_date %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">&laquo;--{{ object.get_previous_post }}</a>
    {% endif %}

    {% if object.get_next_by_modify_date %}
    | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post }}--&raquo;</a>
    {% endif %}
</p>

<p class="date">{{ object.modify_date|date:"j F Y" }}</p>
<br/>

<div class="body">
    {{ object.content|linebreaks }}
</div>

<div>
<b>태그: </b>
{% load tagging_tags %}
{% tags_for_object object as tags %}
{% for tag in tags %}
<a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
{% endfor %}
<a href="{% url 'blog:tag_cloud' %}"><i>[ 태그클라우드 ]</i></a>
</div>

<br/>
<div>
{% load disqus_tags %}
{% disqus_show_comments %}
</div>

</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>포스트 생성/업데이트 - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>포스트를 생성 또는 업데이트 할 수 있는 곳입니다.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.slug.label_tag }} {{ form.slug }}
        </div>

        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

        <div class="form-row">
            {{ form.content.label_tag }} {{ form.content }}
        </div>

        <div class="form-row">
            {{ form.tag.label_tag }} {{ form.tag }}
        </div>

    </fieldset>

    <div class="submit-row">
        <button type="submit" class="btn btn-default">포스트 생성</button>
        <!-- <button type="hidden" name="next" class="btn btn-default" value="{{ next }}"></button> -->
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

<h1>블로그 검색</h1>
<br>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}

            <button type="submit" class="btn btn-default">검색</button>
</form>

<br/><br/>

{% if object_list %}
{% for post in object_list %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

{% elif search_term %}
<b><i>검색한 단어 ({{ search_term }}) 찾지 못했습니다 !</i></b>
{% endif %}

</div>
{% endblock %}

blog/templates/blog/post_test.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

{# <h1>Blog List - test</h1> #}
<h1>블로그 목록 - contains the word '{{ SearchWord }}'</h1>

{% for post in posts %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br/>

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">이전 페이지</a>
        {% endif %}

         {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">다음 페이지</a>
        {% endif %}
    </span>

</div>

</div>
{% endblock %}