blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse

from photo.fields import ThumbnailImageField

from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2)

photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

#--- Add/Change/Update/Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView) :
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView) :
    model = Photo
    success_url = reverse_lazy('photo:index')

#--- Add/Change/Update/Delete for Album
#--- Change/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView) :
    model = Album
    success_url = reverse_lazy('photo:index')


#--- InlineFormSet View
#--- Add/Update for Album
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('photo:album_detail', pk=self.object.id)
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>앨범 변경 - {{user}}</h1>

    <table class="change-list table-striped">
        <tr>
            <th>이름</th>
            <th>설명</th>
            <th>작성자</th>
            <th>업데이트</th>
            <th>삭제</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:album_update' item.id %}">업데이트</a></td>
            <td><a href="{% url 'photo:album_delete' item.id %}">삭제</a></td>
        </tr>
        {% endfor %}
    </table>

</div>


<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/bootstrap.min.js"></script>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>앨범 삭제</h1>

    <form action="." method="post"> {% csrf_token %}
        <p>"{{ object }}"를 정말로 삭제하시겠습니까?</p>
        <button type="submit" class="btn btn-default">앨범 삭제</button>
    </form>

</div>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h2 style="display:inline-block">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

<div class="button">
  <a href="{% url 'photo:index' %}" class="btn btn-primary" role="button">앨범 목록</a>
</div>

    <hr/>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
            <li>{{ photo.title }}</li>
            <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>앨범-사진 모음으로 올리기</h1>

    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">틀렸어요! 아래의 FORM오류를 수정하십시오.</p>
    {% endif %}
    {% if formset.errors %}
    <p class="errornote">틀렸어요! 아래의 FORMSET오류를 수정하십시오.</p>
    {% endif %}


    <h4>앨범 생성 및 변경</h4>

    <fieldset class="aligned">
        <div class="form-row">
            {{ form.name.label_tag }} {{ form.name }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>

    <h4>사진 생성 및 변경</h4>

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.id }}
    <fieldset class="aligned">
        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>
    {% endfor %}

    <div class="submit-row">
        <button type="submit" class="btn btn-default">앨범 생성</button>
    </div>

    <script type="text/javascript">document.getElementById('id_name').focus();</script>

    </form>

</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

    {% for item in object_list %}

    <div class="clear_float">
        <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
        &emsp;<b><i>{{ item.description }}</i></b>
        <br />
        <div class="button">
          <a href="{% url 'photo:photo_add' %}" class="btn btn-primary" role="button">추가</a>
          <a href="{% url 'photo:photo_change' %}" class="btn btn-default" role="button">변경</a>
        </div>
    </div>

    <hr/>

    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
        </div>
        {% endfor %}
    </div>

    {% endfor %}

</div>
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>사진 변경 - {{user}}</h1>

    <table class="change-list table-striped">
        <tr>
            <th>앨범</th>
            <th>제목</th>
            <th>설명</th>
            <th>작성자</th>
            <th>업데이트</th>
            <th>삭제</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.album }}</td>
            <td>{{ item.title }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">업데이트</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">삭제</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% block content %}
<div id="content">

    <h1>사진 삭제</h1>

    <form action="" method="post">{% csrf_token %}
        <p>"{{ object }}"를 정말로 삭제하시겠습니까?</p>
            <button type="submit" class="btn btn-default">사진 삭제</button>
    </form>

</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
<link href="static/css/bootstrap.min.css" rel="stylesheet">

{% block content %}
<div id="content">

    <h2>{{ object.title }}</h2>

    <table class="photo-detail">
    <tr>
    <td>
        <a href="{{ object.image.url }}">
        <img style="max-width:100%" src="{{ object.image.url }}" />
        </a>
    </td>

    <td>
    <ul>
        <li class="nono">사진 설명</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>(blank)</p>{% endif %}
        <li class="nono">업로드 날짜</li>
        <p>{{ object.upload_date }}</p>
        <li  class="nono">앨범 이름</li>
        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
    </ul>
    </td>
    </tr></table>
</div>
<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/bootstrap.min.js"></script>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>사진 생성/업데이트 - {{user}}</h1>

    {% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>생성 또는 업데이트를 할 수 있는 곳입니다.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>

        <div class="form-row">
            {{ form.album.label_tag }} {{ form.album }}
            <button type="button"><a href="{% url 'photo:album_add' %}">앨범 추가하기</a></button>
        </div>

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    <div class="submit-row">
        <button type="submit" class="btn btn-default">사진 생성</button>
    </div>

    <script type="text/javascript">document.getElementById('id_album').focus();</script>

    </form>

</div>
{% endblock %}