blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),

    # Example: /test/
    #url(r'^test/$', TestPostLV.as_view(), name='post_test'),
    # Example: /test/word/
    url(r'^test/(?P<word>[\w]+)/$', TestPostLV.as_view(), name='post_test'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{% block title %}너나들이{% endblock %}</title> 

{% load staticfiles %}
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />


</head>


<body>
  <div id="mymenu">
    <nav class="nav navbar-default" role="navigation">
        <div class = "navbar-header">
          <button type = "button" class = "navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">장고 블로그</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{% url 'home' %}" class="navbar-brand django"><strong>너나들이</strong></a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">기업소개<span class="caret"/>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'bookmark:index' %}">목록</a></li>
                <li><a href="{% url 'bookmark:add' %}">추가</a></li>
                <li><a href="{% url 'bookmark:change' %}">변경</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">신청<span class="caret"/>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'blog:index' %}">목록</a></li>
                <li><a href="{% url 'blog:add' %}">추가</a></li>
                <li><a href="{% url 'blog:change' %}">변경</a></li>
              </ul>
          </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">상품<span class="caret"/>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'photo:index' %}">목록</a></li>
                <li><a href="{% url 'photo:album_add' %}">앨범 추가</a></li>
                <li><a href="{% url 'photo:album_change' %}">앨범 변경</a></li>
                <li><a href="{% url 'photo:photo_add' %}">사진 추가</a></li>
                <li><a href="{% url 'photo:photo_change' %}">사진 변경</a></li>
              </ul>
            </li>
            <li><a href="{% url 'polls:index' %}">커뮤니티</a></li>
            <li><a href="{% url 'blog:post_archive' %}">공지사항</a></li>
            <li><a href="{% url 'blog:search' %}">검색</a></li>
            <li><a href="{% url 'admin:index' %}">관리자</a></li>
          </ul>
          {% if user.is_active %}
          <ul class="nav nav-bar navbar-right">
          <h4 class="welcome">{% firstof user.get_short_name user.get_username %} 님 안녕하세요!
                      <br><a href="{% url 'password_change' %}">비밀번호 바꾸기<i class="fa fa-exchange"></i></a> /
                      <a href="{% url 'logout' %}">로그아웃<i class="fa fa-sign-out"></i></a>
          </h4>
        </ul>
          {% else %}
          <ul class="nav nav-bar navbar-right">
          <h4 class="welcome">환영합니다, 손님<br>
                      <a href="{% url 'login' %}">로그인<i class="fa fa-sign-in"></i></a> /
                      <a href="{% url 'register' %}">회원가입<i class="fa fa-sign-in"></i></a>
          </h4>
        </ul>
        {% endif %}
        </div>
      </nav>
  </div>

  <!-- <script src="static/js/jquery-2.1.3.min.js"></script> -->
  <!-- <script src="static/js/bootstrap.min.js"></script> -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>




{% block content %}


{% endblock %}

{% block footer %}
{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}



{% block title %}1조 블로그{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="static/img/album.jpg">
        <div class="caption">
          <h3>앨범</h3>
          <p>앨범을 만들고 수정해보세요.</p>
          <p><a href="{% url 'photo:album_add' %}" class="btn btn-primary" role="button">추가</a>
            <a href="{% url 'photo:album_change' %}" class="btn btn-default" role="button">변경</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="static/img/photo.jpg">
        <div class="caption">
          <h3>사진</h3>
          <p>사진을 올리고 수정해보세요.</p>
          <p><a href="{% url 'photo:photo_add' %}" class="btn btn-primary" role="button">추가</a>
            <a href="{% url 'photo:photo_change' %}" class="btn btn-default" role="button">변경</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="static/img/blog.jpg">
        <div class="caption">
          <h3>포스트</h3>
          <p>포스트를 만들고 수정해보세요.</p>
          <p>
        	<a href="{% url 'blog:add' %}" class="btn btn-primary" role="button">추가</a>
        	<a href="{% url 'blog:change' %}" class="btn btn-default" role="button">변경</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
<hr style="margin: 10px 0px; border:1px solid black;">

<script src="static/js/jquery-2.1.3.min.js"></script>
<script src="static/js/bootstrap.min.js"></script>

{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; 1조 블로그( 문혜리, 조혜영, 정현진 )
</div>
{% endblock footer %}